import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import MenuBarWidget from "@/shared/widgets/dashboard/MenuBarWidget";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="flex h-screen" suppressHydrationWarning>
        <div className="h-screen w-[14%] bg-red-200 md:w-[8%] lg:w-[14%]">
          <MenuBarWidget />
          hi there
        </div>
        <div className="h-screen w-[86%] bg-green-200 md:w-[92%] lg:w-[86%]">
          right
        </div>
      </body>
    </html>
  );
}
