import type { Metadata } from "next";
import { Fira_Sans } from "next/font/google";
import "../globals.css";
import MenuBarWidget from "@/shared/widgets/dashboard/MenuBarWidget";
import { ThemeProvider } from "@/provider/theme-provider/theme-provider";
import Navbar from "@/components/Navbar";
import { ClerkProvider } from "@clerk/nextjs";

const firaSans = Fira_Sans({
  variable: "--font-fira-sans",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${firaSans.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="flex h-screen" suppressHydrationWarning>
        <ClerkProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {/*left menuBar*/}
            <div className="h-screen w-[14%] md:w-[8%] lg:w-[14%]">
              <MenuBarWidget />
            </div>
            {/*right dashboard*/}
            <div className="h-screen w-[86%] md:w-[92%] lg:w-[86%]">
              <Navbar />
              {children}
            </div>
          </ThemeProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
