import type { Metadata } from "next";
import { Fira_Sans } from "next/font/google";
import "../globals.css";
import Navbar from "@/components/Navbar";

const firaSans = Fira_Sans({
  variable: "--font-fira-sans",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${firaSans.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="flex min-h-full flex-col" suppressHydrationWarning>
        <Navbar></Navbar>
        {children}
        <div className="bg-green-500">footer</div>
      </body>
    </html>
  );
}
